#!/bin/bash

export THREADS=4;
export DROPDIR="/home/ubuntu/finishedplots";
export THREADDIR="/home/ubuntu/threads/thread";

set -e; # exit if any command errors
shopt -s nullglob; # allow empty glob

I=0;
T=0;

while true; do
        for s in $DROPDIR/*.plot; do
                        export T=$(expr "$I" % "$THREADS");

                        export D="$THREADDIR$T/";

                        echo "Moving $s to $D";

                        mkdir -p "$D";
                        mv "$s" "$D";

                        I=$(expr "$I" + 1);
        done

        sleep 5;
done
